<a href="https://colab.research.google.com/github/vitoryago/AI-Machine-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**




In [ ]:
!nvidia-smi

Mon Sep 30 14:33:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


## ***Tensor***
###**Creating Tensor**

---



In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
vector = torch.tensor([[[2,2], [3, 3]],[[7, 7], [3, 3]]])
vector
# vector.ndim
# vector.dtype
vector.shape


torch.Size([2, 2, 2])

### Random Tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
```



In [ ]:
# Create a random Tensor of shape (3, 4)
random_tensor_1 = torch.rand(10, 5, 5, 5)
random_tensor_1
# random_tensor_1.shape
# random_tensor_1.ndim
# random_tensor_1.dtype



torch.Size([10, 5, 5, 5])

### Zero and ones

In [ ]:
zeros = torch.zeros(size=(5,5))
zeros*random_tensor_1
zeros.ndim
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
torch.arange(0, 10)
big_arange = torch.arange(start=0, end=1000, step=45)

In [ ]:
# Creating tensors like
big_arange.dtype

## Zeros as the same shape of big_arrange it's possible to do with ones to
ten_zeros = torch.zeros_like(input=big_arange)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
# dtype is what datatype you want your tensor
# device: we can change between CPU and GPU (cuda)
# requires_grad: you want pytorch to track de gradiants with this tensors operations

float_32_tensor = torch.tensor([3.0, 6.0, 3.3], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = float_32_tensor.type(torch.float32)
float_16_tensor = torch.tensor([3., 6., 9.], dtype=torch.float16)
tensor_test = float_32_tensor * float_16_tensor
tensor_test.dtype

torch.float32

### Manipulating Tensors (tensor operations)

Tensors operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [ ]:
tensor = torch.rand(3, 3)
print(f"Tensor + 10: {tensor+10}")
print(f"Tensor by 10: {tensor * 10}")
print(f"Tensor minus 10: {tensor - 10}")
print(f"Tensor divided by 10: {tensor/10}")
print(f"Try out torch.mul: {torch.mul(tensor, 10)}")


Tensor + 10: tensor([[10.3073, 10.0217, 10.7581],
        [10.8352, 10.4482, 10.3087],
        [10.6158, 10.9847, 10.4006]])
Tensor by 10: tensor([[3.0735, 0.2172, 7.5812],
        [8.3520, 4.4824, 3.0872],
        [6.1582, 9.8474, 4.0063]])
Tensor minus 10: tensor([[-9.6927, -9.9783, -9.2419],
        [-9.1648, -9.5518, -9.6913],
        [-9.3842, -9.0153, -9.5994]])
Tensor divided by 10: tensor([[0.0307, 0.0022, 0.0758],
        [0.0835, 0.0448, 0.0309],
        [0.0616, 0.0985, 0.0401]])
Try out torch.mul: tensor([[3.0735, 0.2172, 7.5812],
        [8.3520, 4.4824, 3.0872],
        [6.1582, 9.8474, 4.0063]])


### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([[9.4462e-02, 4.7187e-04, 5.7474e-01],
        [6.9756e-01, 2.0092e-01, 9.5305e-02],
        [3.7923e-01, 9.6972e-01, 1.6050e-01]])

In [ ]:
# Matrix multiplication
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor([1.1713, 1.1711, 0.8305])
CPU times: user 2.81 ms, sys: 977 µs, total: 3.79 ms
Wall time: 3.67 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 627 µs, sys: 983 µs, total: 1.61 ms
Wall time: 15 ms


tensor([[0.5795, 0.7630, 0.5434],
        [0.8212, 0.5231, 0.8952],
        [1.2584, 0.8493, 0.9314]])

## ***Finding the min, max, mean, sum, etc (tensor aggregation)***

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Tensor min: {torch.min(x)}, {x.min()}")
print(f"Tensor max: {torch.max(x)}, {x.max()}")

# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
print(f"Tensor mean: {torch.mean(x.type(torch.float32))}, {x.type(torch.float32).mean()}")
print(f"Tensor sum: {torch.sum(x)}, {x.sum()}")

#Finding the positional min and max
print(f"Finding the position of the min value {x.argmin()}")
print(f"Finding the position of the max value {x.argmax()}")

Tensor min: 0, 0
Tensor max: 90, 90
Tensor mean: 45.0, 45.0
Tensor sum: 450, 450
Finding the position of the min value 0
Finding the position of the max value 9


## Reshaping, stacking, squeezing and unsqueezxing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in certain way

In [ ]:
#Let's create a tensor
x = torch.arange(1., 10.)

# Add an extra dimension
x_reshaped = x.reshape(3, 3, 1)
x_reshaped, x_reshaped.shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [ ]:
# Change the view (a view of a tensor, shares the same memory as the original input)
z = x.view(3,3)
z, z.shape, x, x.shape

z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=-1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor
print(f"x_reshaped: {x_reshaped}")
print(f"\nx_reshaped shape: {x_reshaped.shape}")
print(f"\nSqueezed: {x_reshaped.squeeze()}")
print(f"\nSqueezed shape: {x_reshaped.squeeze().shape}")
x_squeezed = x_reshaped.squeeze()

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"\nUnsqueezed: {x_squeezed.unsqueeze(dim=0)}")
print(f"\nUnsqueezed shape: {x_squeezed.unsqueeze(dim=0).shape}")

x_reshaped: tensor([[[5.],
         [2.],
         [3.]],

        [[5.],
         [5.],
         [6.]],

        [[5.],
         [8.],
         [9.]]])

x_reshaped shape: torch.Size([3, 3, 1])

Squeezed: tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]])

Squeezed shape: torch.Size([3, 3])

Unsqueezed: tensor([[[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]])

Unsqueezed shape: torch.Size([1, 3, 3])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tesnors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

# Let's index on our new tensor
print(f"x[0]: {x[0]}")
print(f"x[0][0]: {x[0][0]}")
print(f"x[0][0][0]: {x[0][0][0]}")

# You can also use ":" to select "all" of a target dimension
print(f"x[:,0]: {x[:, 0]}")
print(f"x[:, :, 0]: {x[:, :, 0]}")

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(f"x[0, 0, :]: {x[0, 0, :]}")

x[0]: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x[0][0]: tensor([1, 2, 3])
x[0][0][0]: 1
x[:,0]: tensor([[1, 2, 3]])
x[:, :, 0]: tensor([[1, 4, 7]])
x[0, 0, :]: tensor([1, 2, 3])


## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library. And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ...`

In [ ]:
torch.rand(3, 3)

tensor([[0.5538, 0.2241, 0.4979],
        [0.3291, 0.9380, 0.6343],
        [0.4451, 0.4094, 0.3616]])

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1143, 0.5281, 0.5096, 0.4461],
        [0.3470, 0.3147, 0.3414, 0.8654],
        [0.5257, 0.1183, 0.4138, 0.7812]])
tensor([[0.9620, 0.7205, 0.8071, 0.3182],
        [0.5426, 0.1533, 0.2480, 0.3761],
        [0.7314, 0.0356, 0.3718, 0.0578]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
# The manual seed method only works to 1 line after you call it
RANDOM_SEED = 777

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0819, 0.4911, 0.4033, 0.3859],
        [0.8813, 0.8811, 0.7242, 0.5033],
        [0.8249, 0.2634, 0.3112, 0.5948]])
tensor([[0.0819, 0.4911, 0.4033, 0.3859],
        [0.8813, 0.8811, 0.7242, 0.5033],
        [0.8249, 0.2634, 0.3112, 0.5948]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

In [ ]:
!nvidia-smi

Mon Sep 30 19:26:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access with PyTorch


In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# Move tensor back to CPU

tensor_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_on_cpu)

[1 2 3]
